import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../contexts/AuthContext';
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <title>FesSnap（フェススナップ）｜イベント写真共有サービス</title>
          <meta name="description" content="FesSnapはイベントの感動をその場でみんなと共有できる新しい写真共有サービスです。QRコードで簡単参加、リアルタイムで思い出をシェア！" />
          <meta name="keywords" content="FesSnap,フェススナップ,イベント,写真共有,リアルタイム,QRコード,フェス,文化祭,パーティ,思い出,画像,シェア" />
          <meta property="og:title" content="FesSnap（フェススナップ）｜イベント写真共有サービス" />
          <meta property="og:description" content="イベントの感動をその場でみんなと。FesSnapはQRコードで簡単参加、リアルタイムで思い出をシェアできる新しい写真共有サービスです。" />
          <meta property="og:image" content="/logo.png" />
          <meta property="og:url" content="https://fessnap.com/" />
          <meta property="og:type" content="website" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="FesSnap（フェススナップ）｜イベント写真共有サービス" />
          <meta name="twitter:description" content="イベントの感動をその場でみんなと。FesSnapはQRコードで簡単参加、リアルタイムで思い出をシェアできる新しい写真共有サービスです。" />
          <meta name="twitter:image" content="/logo.png" />
          <link rel="canonical" href="https://fessnap.com/" />
          <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "FesSnap（フェススナップ）",
            "url": "https://fessnap.com/",
            "description": "イベントの感動をその場でみんなと共有できる新しい写真共有サービス",
            "logo": "/logo.png"
          })}} />
          <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@700&family=Quicksand:wght@700&family=Nunito:wght@700&family=Rubik:wght@700&family=Rounded+Mplus+1c:wght@700&family=Poppins:wght@700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/logo.png" type="image/png" />
          <link rel="apple-touch-icon" href="/logo.png" type="image/png" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProvider>
            <div className={geistSans.variable + " " + geistMono.variable}>
              {children}
              <Analytics />
            </div>
          </AuthProvider>
        </body>
      </html>
  );
}
